-- validación y reportes

SELECT COUNT(*) FROM PROYECTO1.HECHO_VENTAS;

SELECT 
    t.ANIO,
    u.REGION,
    p.MODALIDAD AS Forma_Pago,
    COUNT(*) AS Total_Transacciones,
    SUM(h.TOTAL_FINAL) AS Dinero_Generado
FROM PROYECTO1.HECHO_VENTAS h
JOIN PROYECTO1.DIM_TIEMPO t ON h.TIEMPO_KEY = t.TIEMPO_KEY
JOIN PROYECTO1.DIM_UBICACION u ON h.CLIENTE_KEY = u.CLIENTE_KEY
JOIN PROYECTO1.DIM_PAGO p ON h.PAGO_KEY = p.PAGO_KEY
GROUP BY t.ANIO, u.REGION, p.MODALIDAD
ORDER BY t.ANIO DESC, Dinero_Generado DESC;

SELECT 
    t.ANIO,
    prod.CATEGORIA,
    v.NOMBRE_COMPLETO AS Vendedor,
    SUM(h.TOTAL_FINAL) AS Total_Vendido
FROM PROYECTO1.HECHO_VENTAS h
JOIN PROYECTO1.DIM_TIEMPO t ON h.TIEMPO_KEY = t.TIEMPO_KEY
JOIN PROYECTO1.DIM_PRODUCTO prod ON h.PRODUCTO_KEY = prod.PRODUCTO_KEY
JOIN PROYECTO1.DIM_VENDEDOR v ON h.VENDEDOR_KEY = v.VENDEDOR_KEY
GROUP BY t.ANIO, prod.CATEGORIA, v.NOMBRE_COMPLETO
ORDER BY Total_Vendido DESC
FETCH FIRST 20 ROWS ONLY; -- Muestra solo los top 20

SELECT 
    t.ANIO,
    u.NOMBRE_CLIENTE,
    SUM(h.TOTAL_FINAL) AS Total_Comprado,
    COUNT(h.ID_HECHO) AS Cantidad_Compras
FROM PROYECTO1.HECHO_VENTAS h
JOIN PROYECTO1.DIM_TIEMPO t ON h.TIEMPO_KEY = t.TIEMPO_KEY
JOIN PROYECTO1.DIM_UBICACION u ON h.CLIENTE_KEY = u.CLIENTE_KEY
GROUP BY t.ANIO, u.NOMBRE_CLIENTE
ORDER BY Total_Comprado DESC
FETCH FIRST 10 ROWS ONLY;