-- construcción de la modelo estrella

-- 1. DIMENSIÓN TIEMPO
-- Necesaria para analizar por Año, Mes, Trimestre (Requisito del PDF)
CREATE TABLE PROYECTO1.DIM_TIEMPO (
    TIEMPO_KEY    NUMBER PRIMARY KEY, -- Usaremos formato YYYYMMDD (ej: 20250101)
    FECHA         DATE,
    ANIO          NUMBER(4),
    TRIMESTRE     VARCHAR2(20),
    MES_NOMBRE    VARCHAR2(20),
    DIA_SEMANA    VARCHAR2(20)
);

-- 2. DIMENSIÓN PRODUCTO
-- Desnormalizamos Producto + Categoría en una sola tabla para consultas rápidas
CREATE TABLE PROYECTO1.DIM_PRODUCTO (
    PRODUCTO_KEY  NUMBER PRIMARY KEY, -- Será el mismo ProductID original
    NOMBRE_PROD   VARCHAR2(100),
    CATEGORIA     VARCHAR2(50),
    MARCA_PROV    VARCHAR2(50),      -- Nombre del proveedor
    TIENE_IVA     VARCHAR2(2)        -- 'SI' o 'NO' para facilitar filtros
);

-- 3. DIMENSIÓN UBICACIÓN (CLIENTE)
-- El PDF pide análisis por "Región". Como tus clientes no tienen región,
-- la "inventaremos" o asignaremos en el proceso ETL para cumplir el requisito.
CREATE TABLE PROYECTO1.DIM_UBICACION (
    CLIENTE_KEY   NUMBER PRIMARY KEY, -- Será el mismo ClienteID
    NOMBRE_CLIENTE VARCHAR2(100),
    REGION        VARCHAR2(50),       -- Costa, Sierra, Oriente (lo llenaremos en ETL)
    CIUDAD        VARCHAR2(50)
);

-- 4. DIMENSIÓN MODALIDAD PAGO
-- Para analizar "Forma de pago preferida"
CREATE TABLE PROYECTO1.DIM_PAGO (
    PAGO_KEY      NUMBER PRIMARY KEY,
    MODALIDAD     VARCHAR2(50),
    TIPO_CREDITO  VARCHAR2(20)       -- 'Corriente' o 'Diferido'
);

-- 5. DIMENSIÓN VENDEDOR
-- Para "El mejor vendedor por categoría..."
CREATE TABLE PROYECTO1.DIM_VENDEDOR (
    VENDEDOR_KEY  NUMBER PRIMARY KEY,
    NOMBRE_COMPLETO VARCHAR2(100)
);

CREATE TABLE PROYECTO1.HECHO_VENTAS (
    ID_HECHO      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Llaves Foráneas a las Dimensiones
    TIEMPO_KEY    NUMBER,
    PRODUCTO_KEY  NUMBER,
    CLIENTE_KEY   NUMBER,
    PAGO_KEY      NUMBER,
    VENDEDOR_KEY  NUMBER,
    
    -- Métricas (Lo que se puede sumar/contar)
    CANTIDAD      NUMBER,
    PRECIO_UNIT   NUMBER(10,2),
    SUBTOTAL      NUMBER(12,2),
    VALOR_IVA     NUMBER(12,2),
    TOTAL_FINAL   NUMBER(12,2),
    
    -- Constraints para asegurar la estrella
    CONSTRAINT FK_HECHO_TIEMPO FOREIGN KEY (TIEMPO_KEY) REFERENCES PROYECTO1.DIM_TIEMPO(TIEMPO_KEY),
    CONSTRAINT FK_HECHO_PROD   FOREIGN KEY (PRODUCTO_KEY) REFERENCES PROYECTO1.DIM_PRODUCTO(PRODUCTO_KEY),
    CONSTRAINT FK_HECHO_CLI    FOREIGN KEY (CLIENTE_KEY) REFERENCES PROYECTO1.DIM_UBICACION(CLIENTE_KEY),
    CONSTRAINT FK_HECHO_PAGO   FOREIGN KEY (PAGO_KEY) REFERENCES PROYECTO1.DIM_PAGO(PAGO_KEY),
    CONSTRAINT FK_HECHO_VEND   FOREIGN KEY (VENDEDOR_KEY) REFERENCES PROYECTO1.DIM_VENDEDOR(VENDEDOR_KEY)
);

-- nuestros datos estan en las tablas normales no estan en el datawarehouse que hemos creado entonces vamos a seguir con los siguentes pasos.

-- 1. Llenar Dimensión VENDEDOR
INSERT INTO PROYECTO1.DIM_VENDEDOR (VENDEDOR_KEY, NOMBRE_COMPLETO)
SELECT EMPLEADOID, NOMBRE || ' ' || APELLIDO 
FROM PROYECTO1.EMPLEADOS;

-- 2. Llenar Dimensión PRODUCTO (CORREGIDO)
INSERT INTO PROYECTO1.DIM_PRODUCTO (PRODUCTO_KEY, NOMBRE_PROD, CATEGORIA, MARCA_PROV, TIENE_IVA)
SELECT 
    p.PRODUCTOID, 
    p.DESCRIPCION, 
    c.NOMBRECAT, 
    pr.NOMBREPROV,
    -- Aquí estaba el error: cambiamos PORCENTAJE_IVA por PORCENTAJEIVA
    CASE WHEN p.PORCENTAJEIVA > 0 THEN 'SI' ELSE 'NO' END 
FROM PROYECTO1.PRODUCTOS p
JOIN PROYECTO1.CATEGORIAS c ON p.CATEGORIAID = c.CATEGORIAID
JOIN PROYECTO1.PROVEEDORES pr ON p.PROVEEDORID = pr.PROVEEDORID;

-- 3. Llenar Dimensión PAGO
INSERT INTO PROYECTO1.DIM_PAGO (PAGO_KEY, MODALIDAD, TIPO_CREDITO)
SELECT 
    ID_MODALIDAD, 
    NOMBRE, 
    CASE WHEN CUOTAS > 0 THEN 'Diferido' ELSE 'Corriente' END
FROM PROYECTO1.MODALIDADPAGO;

-- 4. Llenar Dimensión UBICACIÓN (CLIENTE)
-- El manual pide "Región". Como no la tenemos, usamos una función HASH para
-- asignar aleatoriamente 'Costa', 'Sierra' o 'Oriente' a cada cliente y que sea consistente.
INSERT INTO PROYECTO1.DIM_UBICACION (CLIENTE_KEY, NOMBRE_CLIENTE, CIUDAD, REGION)
SELECT 
    CLIENTEID, 
    NOMBRECLI, 
    'Ciudad Generica', -- Dato quemado
    CASE MOD(CLIENTEID, 3) 
        WHEN 0 THEN 'Costa' 
        WHEN 1 THEN 'Sierra' 
        ELSE 'Oriente' 
    END -- Transformación para cumplir requisito de Región
FROM PROYECTO1.CLIENTES;

commit;

-- vamos a llenar la dimensión timepo(especial)

DECLARE
    v_FechaInicio DATE := TO_DATE('01/01/2020','DD/MM/YYYY');
    v_FechaFin    DATE := TO_DATE('31/12/2025','DD/MM/YYYY');
    v_FechaActual DATE;
    v_Key         NUMBER;
BEGIN
    v_FechaActual := v_FechaInicio;
    
    WHILE v_FechaActual <= v_FechaFin LOOP
        -- Generar Key formato YYYYMMDD (Ej: 20240115)
        v_Key := TO_NUMBER(TO_CHAR(v_FechaActual, 'YYYYMMDD'));
        
        INSERT INTO PROYECTO1.DIM_TIEMPO (TIEMPO_KEY, FECHA, ANIO, TRIMESTRE, MES_NOMBRE, DIA_SEMANA)
        VALUES (
            v_Key,
            v_FechaActual,
            EXTRACT(YEAR FROM v_FechaActual),
            'T' || TO_CHAR(v_FechaActual, 'Q'), -- Trimestre (T1, T2...)
            TO_CHAR(v_FechaActual, 'MONTH', 'NLS_DATE_LANGUAGE=SPANISH'), -- Mes en español
            TO_CHAR(v_FechaActual, 'DAY', 'NLS_DATE_LANGUAGE=SPANISH')    -- Día en español
        );
        
        v_FechaActual := v_FechaActual + 1; -- Avanzar un día
    END LOOP;
    
    COMMIT;
END;
/

-- vamos a llenar la carga hechos esta es la tabla masiva
-- Este script toma tus 100,000 órdenes y su detalle, calcula el dinero real (Precio * Cantidad) y el IVA, y lo guarda en el formato OLAP.

INSERT INTO PROYECTO1.HECHO_VENTAS (
    TIEMPO_KEY, PRODUCTO_KEY, CLIENTE_KEY, PAGO_KEY, VENDEDOR_KEY,
    CANTIDAD, PRECIO_UNIT, SUBTOTAL, VALOR_IVA, TOTAL_FINAL
)
SELECT 
    -- 1. Construir el Key de Tiempo basado en la fecha de la orden
    TO_NUMBER(TO_CHAR(o.FECHAORDEN, 'YYYYMMDD')) AS TIEMPO_KEY,
    
    -- 2. Llaves directas
    d.PRODUCTOID AS PRODUCTO_KEY,
    o.CLIENTEID  AS CLIENTE_KEY,
    o.ID_Modalidad AS PAGO_KEY,
    o.EMPLEADOID AS VENDEDOR_KEY,
    
    -- 3. Métricas Calculadas
    d.CANTIDAD,
    p.PRECIOUNIT,
    (d.CANTIDAD * p.PRECIOUNIT) AS SUBTOTAL, -- Cantidad * Precio
    (d.CANTIDAD * p.PRECIOUNIT * p.PORCENTAJEIVA) AS VALOR_IVA, -- Calculo de IVA real
    ((d.CANTIDAD * p.PRECIOUNIT) * (1 + p.PORCENTAJEIVA)) AS TOTAL_FINAL
    
FROM PROYECTO1.ORDENES o
JOIN PROYECTO1.DETALLE_ORDENES d ON o.ORDENID = d.ORDENID
JOIN PROYECTO1.PRODUCTOS p ON d.PRODUCTOID = p.PRODUCTOID;

COMMIT;