-- ==========================
-- 1. TABLA CATEGORIAS
-- ==========================
CREATE TABLE PROYECTO1.CATEGORIAS (
    CATEGORIAID   NUMBER(10,0)  NOT NULL,
    NOMBRECAT     CHAR(50 BYTE) NOT NULL,
    CONSTRAINT PK_CATEGORIAS PRIMARY KEY (CATEGORIAID)
);

-- ==========================
-- 2. TABLA PROVEEDORES
-- ==========================
CREATE TABLE PROYECTO1.PROVEEDORES (
    PROVEEDORID   NUMBER(10,0)  NOT NULL,
    NOMBREPROV    CHAR(50 BYTE) NOT NULL,
    CONTACTO      CHAR(50 BYTE),
    CELUPROV      CHAR(12 BYTE),
    FIJOPROV      CHAR(12 BYTE),
    CONSTRAINT PK_PROVEEDORES PRIMARY KEY (PROVEEDORID)
);

-- ==========================
-- 3. TABLA PRODUCTOS
-- ==========================
CREATE TABLE PROYECTO1.PRODUCTOS (
    PRODUCTOID   NUMBER(10,0)  NOT NULL,
    CATEGORIAID  NUMBER(10,0)  NOT NULL,
    PROVEEDORID  NUMBER(10,0)  NOT NULL,
    DESCRIPCION  CHAR(50 BYTE),
    PRECIOUNIT   NUMBER(10,2),
    EXISTENCIA   NUMBER(10,0),
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (PRODUCTOID),
    CONSTRAINT FK_PRODUCTO_CATE_PROD_CATEGORI 
        FOREIGN KEY (CATEGORIAID) 
        REFERENCES PROYECTO1.CATEGORIAS (CATEGORIAID),
    CONSTRAINT FK_PRODUCTO_PROV_PROD_PROVEEDOR 
        FOREIGN KEY (PROVEEDORID) 
        REFERENCES PROYECTO1.PROVEEDORES (PROVEEDORID)
);

-- ==========================
-- 4. TABLA EMPLEADOS
-- ==========================
CREATE TABLE PROYECTO1.EMPLEADOS (
    EMPLEADOID   NUMBER(10,0)  NOT NULL,
    NOMBRE       CHAR(30 BYTE) NOT NULL,
    APELLIDO     CHAR(30 BYTE) NOT NULL,
    FECHA_NAC    DATE,
    REPORTA_A    NUMBER(10,0),
    EXTENSION    NUMBER(10,0),
    CONSTRAINT PK_EMPLEADOS PRIMARY KEY (EMPLEADOID),
    CONSTRAINT FK_EMPLEADO_REPORTA 
        FOREIGN KEY (REPORTA_A)
        REFERENCES PROYECTO1.EMPLEADOS (EMPLEADOID)
);

-- ==========================
-- 5. TABLA CLIENTES
-- ==========================
CREATE TABLE PROYECTO1.CLIENTES (
    CLIENTEID        NUMBER(10,0)  NOT NULL,
    CEDULA_RUC       CHAR(10 BYTE) NOT NULL,
    NOMBRECLI        CHAR(30 BYTE) NOT NULL,
    NOMBRECONTACTO   CHAR(50 BYTE),
    DIRECCIONCLI     CHAR(50 BYTE),
    FAX              CHAR(12 BYTE),
    EMAIL            CHAR(50 BYTE),
    CELULAR          CHAR(12 BYTE),
    FIJO             CHAR(12 BYTE),
    CONSTRAINT PK_CLIENTES PRIMARY KEY (CLIENTEID)
);

-- ==========================
-- 6. TABLA ORDENES
-- ==========================
CREATE TABLE PROYECTO1.ORDENES (
    ORDENID     NUMBER(10,0) NOT NULL,
    EMPLEADOID  NUMBER(10,0) NOT NULL,
    CLIENTEID   NUMBER(10,0) NOT NULL,
    FECHAORDEN  DATE,
    DESCUENTO   NUMBER(5,2),
    CONSTRAINT PK_ORDENES PRIMARY KEY (ORDENID),
    CONSTRAINT FK_ORDENES_EMPLE_ORD_EMPLEADO 
        FOREIGN KEY (EMPLEADOID)
        REFERENCES PROYECTO1.EMPLEADOS (EMPLEADOID),
    CONSTRAINT FK_ORDENES_CLIEN_ORD_CLIENTES 
        FOREIGN KEY (CLIENTEID)
        REFERENCES PROYECTO1.CLIENTES (CLIENTEID)
);

-- ==========================
-- 7. TABLA DETALLE_ORDENES
-- ==========================
CREATE TABLE PROYECTO1.DETALLE_ORDENES (
    ORDENID     NUMBER(10,0) NOT NULL,
    DETALLEID   NUMBER(10,0) NOT NULL,
    PRODUCTOID  NUMBER(10,0) NOT NULL,
    CANTIDAD    NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_DETALLE_ORDENES 
        PRIMARY KEY (ORDENID, DETALLEID),
    CONSTRAINT FK_DETALLE_ORDEN_DET_ORDENES 
        FOREIGN KEY (ORDENID)
        REFERENCES PROYECTO1.ORDENES (ORDENID),
    CONSTRAINT FK_DETALLE_PROD_DETA_PRODUCTO 
        FOREIGN KEY (PRODUCTOID)
        REFERENCES PROYECTO1.PRODUCTOS (PRODUCTOID)
);

-- modificación(agregar columna de iva productos)

ALTER TABLE PRODUCTOS
ADD PorcentajeIVA NUMBER(4,2) DEFAULT 0.15 NOT NULL;

-- 2. creando la tabal modalidad de pago
-- nuestro documento exige registrar efectivo, transferencias y tarjetas con cuotas.

CREATE TABLE ModalidadPago(
  ID_Modalidad NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Nombre VARCHAR2(50),
  Cuotas NUMBER DEFAULT 0
);

-- vamos a insertar datos fijos dentro de la tabla
INSERT INTO MODALIDADPAGO (Nombre,Cuotas) VALUES ('Efectivo',0);
INSERT INTO MODALIDADPAGO (Nombre,Cuotas) VALUES ('Transferencias',0);
INSERT INTO MODALIDADPAGO (Nombre,Cuotas) VALUES ('Tarjeta de credito',3);
INSERT INTO MODALIDADPAGO (Nombre,Cuotas) VALUES ('Tarjeta de credito',12);

COMMIT;

-- conectar pedidos con modalidad 

ALTER TABLE ordenes
ADD ID_Modalidad NUMBER;

ALTER TABLE ordenes 
ADD CONSTRAINT FK_Pedidos_Modalidad 
FOREIGN KEY (ID_Modalidad) REFERENCES ModalidadPago(ID_Modalidad);

select * from ordenes, DETALLE_ORDENES;

-- para ingresar los 1000 datos, debemos insertar quien compra y a quien compra

BEGIN
    -- 1. Insertar 5 Categorias
    FOR i IN 1..5 LOOP
        INSERT INTO PROYECTO1.CATEGORIAS (CATEGORIAID, NOMBRECAT) 
        VALUES (i, 'Categoria ' || i);
    END LOOP;

    -- 2. Insertar 10 Proveedores
    FOR i IN 1..10 LOOP
        INSERT INTO PROYECTO1.PROVEEDORES (PROVEEDORID, NOMBREPROV, CONTACTO, CELUPROV) 
        VALUES (i, 'Proveedor ' || i, 'Contacto ' || i, '099999999');
    END LOOP;

    -- 3. Insertar 5 Empleados
    FOR i IN 1..5 LOOP
        INSERT INTO PROYECTO1.EMPLEADOS (EMPLEADOID, NOMBRE, APELLIDO, FECHA_NAC) 
        VALUES (i, 'Empleado', 'Num ' || i, SYSDATE - 10000);
    END LOOP;

    -- 4. Insertar 20 Clientes (CORREGIDO)
    -- Usamos LPAD para rellenar con ceros a la izquierda hasta llegar a 10 dígitos exactos
    -- Ejemplo: el ID 1 se convierte en '0000000001', el ID 20 en '0000000020'
    FOR i IN 1..20 LOOP
        INSERT INTO PROYECTO1.CLIENTES (CLIENTEID, CEDULA_RUC, NOMBRECLI, DIRECCIONCLI) 
        VALUES (i, LPAD(i, 10, '0'), 'Cliente Generico ' || i, 'Direccion ' || i);
    END LOOP;

    -- 5. Insertar 200 Productos
    FOR i IN 1..200 LOOP
        INSERT INTO PROYECTO1.PRODUCTOS (PRODUCTOID, CATEGORIAID, PROVEEDORID, DESCRIPCION, PRECIOUNIT, EXISTENCIA, PorcentajeIVA) 
        VALUES (
            i, 
            TRUNC(DBMS_RANDOM.VALUE(1, 6)),   
            TRUNC(DBMS_RANDOM.VALUE(1, 11)),  
            'Producto ' || i, 
            ROUND(DBMS_RANDOM.VALUE(10, 100), 2), 
            1000,
            CASE WHEN i <= 100 THEN 0.15 ELSE 0.00 END 
        );
    END LOOP;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Datos Maestros creados exitosamente.');
END;
/

-- insertando los 100,000 pedidos

DECLARE
    -- Configuración
    v_TotalOrdenes   NUMBER := 100000;
    
    -- Variables para IDs aleatorios
    v_EmpleadoID     NUMBER;
    v_ClienteID      NUMBER;
    v_ModalidadID    NUMBER;
    v_FechaOrden     DATE;
    
    -- Variables para el detalle
    v_NumProductos   NUMBER; -- Cuántos items tendrá la orden
    v_ProductoID     NUMBER;
    v_Cantidad       NUMBER;
    
    -- Fecha inicio para cálculo (01/01/2020)
    v_FechaInicio    DATE := TO_DATE('01/01/2020','DD/MM/YYYY');
    
BEGIN
    FOR i IN 1..v_TotalOrdenes LOOP
        
        -- A. Generar Datos de Cabecera (ORDENES)
        -- Seleccionamos IDs aleatorios basados en los rangos que creamos en el Paso 1
        v_EmpleadoID  := TRUNC(DBMS_RANDOM.VALUE(1, 6));  -- IDs 1 al 5
        v_ClienteID   := TRUNC(DBMS_RANDOM.VALUE(1, 21)); -- IDs 1 al 20
        
        -- Tu tabla ModalidadPago tiene 4 registros insertados manualmente.
        -- Asumimos que los IDs generados fueron 1, 2, 3, 4 (o buscamos al azar).
        -- Nota: Si usaste Identity, los IDs deberían ser secuenciales. Usaremos 1-4.
        v_ModalidadID := TRUNC(DBMS_RANDOM.VALUE(1, 5)); 
        
        -- Fecha aleatoria: 01/01/2020 + (0 a 2190 días) -> Cubre hasta finales de 2025
        v_FechaOrden  := v_FechaInicio + TRUNC(DBMS_RANDOM.VALUE(0, 2191));
        
        -- B. Insertar la Orden
        -- Usamos 'i' como ORDENID ya que es único en este bucle
        INSERT INTO ORDENES (ORDENID, EMPLEADOID, CLIENTEID, FECHAORDEN, DESCUENTO, ID_Modalidad)
        VALUES (i, v_EmpleadoID, v_ClienteID, v_FechaOrden, 0, v_ModalidadID);
        
        -- C. Generar el Detalle (DETALLE_ORDENES)
        -- Requisito: "Cada pedido debe tener de 3 a 10 productos"
        v_NumProductos := TRUNC(DBMS_RANDOM.VALUE(3, 11)); 
        
        FOR j IN 1..v_NumProductos LOOP
             -- Producto aleatorio (IDs 1 al 200)
             v_ProductoID := TRUNC(DBMS_RANDOM.VALUE(1, 201));
             
             -- Cantidad aleatoria (1 a 50)
             v_Cantidad := TRUNC(DBMS_RANDOM.VALUE(1, 51));
             
             INSERT INTO DETALLE_ORDENES (ORDENID, DETALLEID, PRODUCTOID, CANTIDAD)
             VALUES (i, j, v_ProductoID, v_Cantidad);
        END LOOP;
        
        -- D. Commit parcial para no saturar la memoria RAM
        -- Guardamos cambios cada 5,000 órdenes
        IF MOD(i, 5000) = 0 THEN
            COMMIT;
        END IF;
        
    END LOOP;
    
    -- Commit final para asegurar los últimos registros
    COMMIT;
END;
/


-- vamos a comprobar si todo salio bien(opcional)

-- Verificar cantidad de órdenes (Debe dar 100,000)
SELECT COUNT(*) AS Total_Ordenes FROM ORDENES;

-- Verificar detalle masivo (Debe dar aprox 650,000 registros)
SELECT COUNT(*) AS Total_Detalles FROM DETALLE_ORDENES;

-- Verificar que las fechas estén bien distribuidas (debe salir 2020, 2021... 2025)
SELECT EXTRACT(YEAR FROM FECHAORDEN) AS Anio, COUNT(*) 
FROM ORDENES 
GROUP BY EXTRACT(YEAR FROM FECHAORDEN)
ORDER BY Anio;


